  - name: cp mysql-rpms to remot host:/root/cdh/mysql-rpms
    copy: src=mysql-rpms dest=/root/cdh/
  - name: install mysql
    command: chdir=/root/cdh/mysql-rpms rpm -Uvh *.rpm --force creates=/usr/sbin/mysqld
  - name: copy my.cnf 
    template: src=my.cnf dest=/etc/my.cnf backup=true
  - name: start mysql
    service: name=mysql state=started
  - name: init mysql
    script: scripts/mysql_cdh_init.sh creates=/tmp/cdh_mysql_init
  
  - name: cp parcels/* to remot host:/opt/cloudera/parcel-repo/
    copy: src=parcels/ dest=/opt/cloudera/parcel-repo/

  - name: cp cdh server service file to remot host:/etc/init.d/cdh
    copy: src=scripts/cdh dest=/etc/init.d/cdh mode=0755
  - name: create cdh user
    user: name=cloudera-scm create_home=no home=/opt/cm-5.12.2/run/cloudera-scm-server shell=/bin/false
  - name: create server runtime lib
    file: path=/var/lib/cloudera-scm-server state=directory owner=cloudera-scm group=cloudera-scm 
  - name: chown cloudera-scm /opt/cm*
    file: path=/opt/cm-5.12.2  state=directory owner=cloudera-scm group=cloudera-scm recurse=yes

  - name: config local ntpd
    lineinfile: dest=/etc/ntp.conf regexp="127.127"  line="server 127.127.1.0\nfudge 127.127.1.0  stratum 10"
    notify: restart ntpd
  - name: kill pre supervisor (in case agent start failed)
    script: scripts/kill_supervisor.sh 
    tags: superkill
  - name: start cdh server
    service: name=cdh state=started enabled=true
  - name: wait for 7180
    wait_for: port=7180

