# Default values for kuai.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  configfile: global
  mysql:
    # kuai业务系统使用 sql数据库地址
    baseUrl: 192.168.0.8:3306
    # kuai库名
    dbName: kuai
    # kuai数据库用户名
    username: root
    # kuai数据库密码
    password: 123456
    # kuai-grafana监控使用 sql数据库地址
    grafanaBaseUrl:  192.168.0.8:3306
    # grafana数据库名
    grafanaDbName: grafana
    # grafana数据库用户名
    grafanaUsername: root
    # grafana数据库用密码
    grafanaPassword: 123456
  glusterfs:
    endpoints: glusterfs-kuai
    # glusterfs挂载盘名称
    path: dir_rep_vol_01
    # glusterfs IP地址
    addresses:
      - ip: 192.168.0.9
      - ip: 192.168.0.10
      - ip: 192.168.0.11
  image:
    #harbor配置
    repositoryHost: harbor01.io
  hostAliases:
    #harbor地址
    - ip: "192.168.0.9"
      hostnames: "harbor01.io"
  kuai:
    #镜像库
    imageRepository:
      address: http://harbor01.io
      prefix: harbor01.io
      user: admin
      password: Harbor12345
    #请求用户kerberos信息服务
    kerberos:
      url: http://192.168.54.45:8170
    livyServers: 192.168.29.158
  #单点登陆配置  uas/sso 2选1  invalid false 时，走所属配置
  uas:
    invalid: false
    login:
      system: ocean #uas控制台接入应用列表 应用名
  cache:
    redis:
      enabled: true
      clusterid: client1
      clustersnamespace: app1
      clustersnodes: 192.168.0.12:7001,192.168.0.12:7002,192.168.0.12:7003,192.168.0.13:7001,192.168.0.13:7002,192.168.0.12:7003
      clusterspassword: 
    kafka:
      enabled: true
      consumer:
        bootstrapServers: 192.168.0.12:9092,192.168.0.13:9092,192.168.0.14:9092
        topic: ocean_gravity_job_status
  kuaiTrain:
    cephMonitors:
    autoMLImage: harbor01.io/automl/automl_based_centos7-py36-tf1.5-cpu:v0.1.0
    autoMLCpu: 1
    autoMLMen: 1
    autoMLGpu: 0
    tensorBoardImage: harbor01.io/train/centos7-py36-tf1.5-cpu:latest
  kuaiGraph:
    hiveUrl: jdbc:hive2://192.168.0.17:21066/%s;principal=hive/yz-10-222-29-54.h.abchost.local@HADOOP.COM;hive.server2.proxy.user=dwetl?useUnicode=true&characterEncoding=UTF-8
    userName: hive
    krbUser: hive/ocean@HADOOP.COM
    #需cp krb5.conf覆盖/mnt/user/目krb5.conf
    krbConfigFile: /ceph/krb5.conf
    #默认不用动
    keytabFile: /export/kerberos/hive.keytab
    graph:
      dataSourceKind: local|LocalPathStructService,mysql|MySqlStructService,hive|HiveStructService
      image: harbor01.io/graph/visual_modeling_env:latest
      image: harbor01.io/graph/visual_modeling_env:latest
